### ISSUE TITLE
For "Repeated method in the superclasses" & "Subclass responsibility not defined" - would be nice to get a list if you can't highlight

### ISSUE THREAD

**Issue by pdebruic** [Uko/QualityAssistant#13]
In Pharo 4 on Mac.

After selecting a class, when clicking on this critic nothing is highlighted.  When that happens it would be great if you could open a list where you could select the offending method(s) and have a button to browse it.

**Comment by Uko** [comment]
Hi than you for using QualityAssistant and reporting the issues.

_Repeated method in superclass_ was already reported in #4 and is already resolved in some way in Pharo 5.

_Subclass responsibility not defined_ was reported in #2. I am still looking for a way to solve this in a nice way. Stay tuned
