### ISSUE TITLE
not refreshing when "message sent but not implemented" is fixed

### ISSUE THREAD

**Issue by estebanlm** [Uko/QualityAssistant#18]
I get that message, then I implement the missing method and smell does not disappear from list. 
I suppose create a new method should reset all method caches?

**Comment by estebanlm** [comment]
I forget to mark it as bug... but I don't know if I'm allowed :)

**Comment by Uko** [comment]
Yes, it's one of the reasons why there is a refresh button for now. It's also not that trivial to remove the critics cache (but can be done).

Another option that I am considering is either not to cache this rules or make a relations between rules and critics, to know what should be flushed. For now this is still WIP

**Comment by Uko** [comment]
For now caching was removed all together, so the issue is not more relevant
