### ISSUE TITLE
Anonymous classes should not be criticized by QA

### ISSUE THREAD

**Issue by peteruhnak** [Uko/QualityAssistant#21]
Browsing through anonymous classes shows error triggered by QA because they are... anonymous. :)

``` st
cls := Object newAnonymousSubclass.
cls compile: 'method ^ 1'.
cls browse.
```

When you then select the method `method` an error appears 
_KeyNotFound: key 'a subclass of Object' not found in SystemDictionary_

the error itself is to be expected, because anonymous classes are not in the SystemDictionary, however critic shouldn't criticize them, because RB rules do not understand them.

Alternatively it could be fixed on RB side (which may or may not be even possible), but I would argue that anonymous classes are created primarily in ad-hoc fashion and thus their quality is not of relevance.

**Comment by Uko** [comment]
Thank you for the report. The issue was gracefully fixed in the rule itself in [case 16874](https://pharo.fogbugz.com/f/cases/16874)
